### ISSUE TITLE
Request: readme and bugfix

### ISSUE THREAD

**Issue by jfrench206** [rmathur101/affordable_housing#1]
Hi Rohan,

I'm curious about this project, but it's a little dense from my POV - would you be willing to make a Readme file on Github, with instructions about how to get started? 

Also, I tried running `node server.js` after cloning the project, but I get an error from body-parser: `body-parser deprecated undefined extended: provide extended option server.js:23:21`

Looking into how to fix it...might fork and create a PR if I can solve it. I'm new to this Github collaborative programming thing!

Cheers,
Jesse

**Comment by jfrench206** [comment]
Update: solved the above by editing server.js line 23: `app.use(body_parser.urlencoded({extended:true}));` - reading the docs for body-parser, it looks like they want you to specify the behavior.

I'm still getting an error though, which I have no idea how to fix:

```
$ node server.js
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1349:19)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Function.listen (/home/jesse/affordable_housing/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/jesse/affordable_housing/server.js:26:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

**Comment by rmathur101** [comment]
ah yeah this was a very quick prototype so apologies for the quality of the documentation and code. your issue here is that the port is specified to 80, you’ll want to specify the port as 3000 (or something reasonable) for your local development (it should be in app.js - i think that’s what i called it) port 80 is reserved for access to the web and is being used on production.

**Comment by jfrench206** [comment]
Aha! Thanks for the context. Your project was mentioned in the latest Open Austin newsletter, FYI, with a link to this Github repo...

I changed the port (in server.js) and the server runs now - I also had to change the pathnames on lines 53-55 in server.js to match where I have the project on my local drive. Now everything is loading and running properly!

**Comment by rmathur101** [comment]
awesome! happy to hear it! hoping to work on this some more soon and would love the help if there is any interest! at the moment, still talking to users and figuring out what the right thing to build is.

**Comment by jfrench206** [comment]
My main priority right now is my job search, but I'm tentatively interested in helping out! Keep me posted please.
